version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - encrypted_files:/app/encrypted_files
      - ./backend/certs:/app/certs
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=your-super-secret-django-key-change-this-in-production
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - JWT_ALGORITHM=HS256
      - CORS_ALLOWED_ORIGINS=https://localhost:3000
      - MFA_ISSUER_NAME=YourApp
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - ./frontend/certs:/app/certs
    environment:
      - HTTPS=true
      - SSL_CRT_FILE=/app/certs/cert.pem
      - SSL_KEY_FILE=/app/certs/key.pem
      - REACT_APP_API_URL=https://localhost:8000
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_node_modules:
  frontend_node_modules:
  encrypted_files:

networks:
  app-network:
    driver: bridge 