version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      # Share SSL certificates for HTTPS
      - ./backend/certs:/app/certs
    environment:
      - HTTPS=true
      - SSL_CRT_FILE=/app/certs/cert.pem
      - SSL_KEY_FILE=/app/certs/key.pem
      - WDS_SOCKET_PORT=0  # Required for hot reloading
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=dev-secret-key
      - JWT_SECRET_KEY=dev-jwt-key
      - JWT_ALGORITHM=HS256
      - CORS_ALLOWED_ORIGINS=https://localhost:3000 