# Generated by Django 5.1.4 on 2025-01-11 12:23

from django.db import migrations, models

def forward_func(apps, schema_editor):
    KeyPair = apps.get_model('kms', 'KeyPair')
    for key_pair in KeyPair.objects.all():
        key_pair.username = key_pair.user.username
        key_pair.save()

def reverse_func(apps, schema_editor):
    User = apps.get_model('users', 'User')
    KeyPair = apps.get_model('kms', 'KeyPair')
    for key_pair in KeyPair.objects.all():
        user = User.objects.get(username=key_pair.username)
        key_pair.user = user
        key_pair.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0001_initial'),
    ]

    operations = [
        # First add the username field allowing null temporarily
        migrations.AddField(
            model_name='keypair',
            name='username',
            field=models.CharField(max_length=150, null=True, db_index=True),
        ),
        # Populate the username field
        migrations.RunPython(forward_func, reverse_func),
        # Make username non-nullable
        migrations.AlterField(
            model_name='keypair',
            name='username',
            field=models.CharField(max_length=150, null=False, db_index=True),
        ),
        # Remove the old user field
        migrations.RemoveField(
            model_name='keypair',
            name='user',
        ),
        # Create KeyAccess model
        migrations.CreateModel(
            name='KeyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_owner_username', models.CharField(db_index=True, max_length=150)),
                ('shared_with_username', models.CharField(db_index=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'key_access',
                'unique_together': {('key_owner_username', 'shared_with_username')},
            },
        ),
    ]
