# Generated by Django 5.1.4 on 2025-01-11 06:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('encrypted_key', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploaded_by', 'created_at'], name='files_uploade_b8b03e_idx'), models.Index(fields=['file_name'], name='files_file_na_85b89e_idx')],
            },
        ),
    ]
