# Generated by Django 5.1.4 on 2025-01-11 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_username', models.CharField(db_index=True, max_length=150)),
                ('permission_type', models.CharField(choices=[('VIEW', 'View'), ('DOWNLOAD', 'Download')], default='VIEW', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.file')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_shares',
                'ordering': ['-created_at'],
                'unique_together': {('file', 'shared_with_username')},
            },
        ),
    ]
