# Generated by Django 5.1.4 on 2025-01-11 15:39

import django.db.models.deletion
import django.utils.timezone
import files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_fileshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=files.models.generate_uuid, max_length=64, unique=True)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_links', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareable_links', to='files.file')),
            ],
            options={
                'db_table': 'shareable_links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file', 'created_at'], name='shareable_l_file_id_5f143d_idx'), models.Index(fields=['created_by', 'created_at'], name='shareable_l_created_7470d8_idx')],
            },
        ),
    ]
